<h1> Creation of arrays, basic operations, type conversions, simple statistics.

In [7]:
import numpy as np
from IPython.display import display

# Generation examples
arr = np.arange(9)
mtx = np.random.uniform(size=9).reshape(3,3)
I = np.eye(4)

arr, mtx, I

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[0.24993027, 0.75286824, 0.06148405],
        [0.26945856, 0.37816597, 0.32366581],
        [0.50197362, 0.76524414, 0.3596917 ]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [8]:
random_vector = np.random.uniform(size=100)
random_vector = random_vector * np.random.uniform(size=100, low=0, high=100)


In [9]:
# Describe

display(f"sum = {random_vector.sum():.2f}")
display(f"mean = {random_vector.mean():.2f}")
display(f"median = {np.median(random_vector):.2f}")
display(f"standard_deviation = {random_vector.std():.2f}")



'sum = 2409.25'

'mean = 24.09'

'median = 17.86'

'standard_deviation = 21.72'

In [10]:
random_vector.dtype

dtype('float64')

In [11]:
random_vector = random_vector.astype(int)

random_vector, random_vector.dtype

(array([15,  0, 38,  2,  2, 22, 11, 30,  7, 33, 23, 89, 29, 26, 29, 45, 39,
        42, 29,  6, 46,  7, 48,  1, 16,  1, 17,  5, 11, 13, 38,  5, 17,  1,
         6, 12, 60, 17,  7, 23, 14, 13, 31, 74,  8,  2,  0, 14, 41,  1,  0,
        44,  1, 10, 12, 28,  5, 20, 19, 20,  2, 11, 58, 18,  9, 48, 36, 89,
        85, 24, 14,  0, 18, 17, 27, 67, 65, 22, 49,  7, 24, 47, 11, 36,  7,
         6, 79, 18, 15, 25,  2,  8, 23,  1,  2, 37,  8, 20, 74, 20]),
 dtype('int64'))