<h1> Creation of arrays, basic operations, type conversions, simple statistics.

In [12]:
import numpy as np

In [13]:
# Generation examples
arr = np.arange(9)
mtx = np.random.uniform(size=9).reshape(3,3)
I = np.eye(4)

arr, mtx, I

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[0.63266388, 0.27599878, 0.10010515],
        [0.21990531, 0.81323843, 0.06443264],
        [0.11235171, 0.50534265, 0.51304891]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [14]:
random_vector = np.random.uniform(size=100)
random_vector = random_vector * np.random.uniform(size=100, low=0, high=100)


In [15]:
# Describe

display(f"sum = {random_vector.sum():.2f}")
display(f"mean = {random_vector.mean():.2f}")
display(f"median = {np.median(random_vector):.2f}")
display(f"standard_deviation = {random_vector.std():.2f}")



'sum = 2553.44'

'mean = 25.53'

'median = 18.43'

'standard_deviation = 23.55'

In [16]:
random_vector.dtype

dtype('float64')

In [17]:
random_vector = random_vector.astype(int)

random_vector, random_vector.dtype

(array([43, 13,  2,  6,  9, 23, 21, 20, 53, 59, 49,  3,  6, 59, 58, 65, 12,
         2,  9, 34,  0, 40,  3, 35, 71, 65,  2, 38, 77,  0,  4, 39,  7, 10,
        18, 40, 69, 47, 24,  0, 31,  0,  2, 34,  0,  4, 78, 18, 37, 20, 12,
         2, 14, 42, 20, 14,  6,  3, 38, 33, 18, 34, 89, 32, 17,  2, 76, 10,
        65, 34, 34,  3, 18, 47,  3,  5, 21, 45,  0,  7,  8,  7,  2,  8,  3,
        35,  0, 16, 75, 73,  1,  4,  2, 35, 12, 27, 14,  0, 62, 19]),
 dtype('int64'))