In [34]:
import numpy as np

In [35]:
## make 4x4 matrix
A = np.random.uniform(size=16, low=-10, high=10).reshape(4,4)

A

array([[ 8.64921207, -2.27000688, -6.64706449,  6.68651634],
       [ 5.95473402,  2.05777389,  4.34815019,  1.77461513],
       [ 9.50322566,  4.79990892,  7.8571927 ,  4.84246761],
       [ 4.33044799,  9.88503781,  1.55092681,  9.43672251]])

In [36]:
## slice 2x2 from inside
A[1:3,1:3]

array([[2.05777389, 4.34815019],
       [4.79990892, 7.8571927 ]])

In [37]:
## values above first, second, third quantile
def show_values_above_quantile(x, I):
    q = np.quantile(I, x)
    mask_q1 = I>q
    return q, np.sort(I[mask_q1])

display(f"first quantile = {show_values_above_quantile(0.25,A)[0]:.2f}")
display(np.round(show_values_above_quantile(0.25,A)[1],2))

display(f"second quantile = {show_values_above_quantile(0.5,A)[0]:.2f}")
display(np.round(show_values_above_quantile(0.5,A)[1],2))

display(f"third quantile = {show_values_above_quantile(0.75,A)[0]:.2f}")
display(np.round(show_values_above_quantile(0.75,A)[1],2))


'first quantile = 1.99'

array([2.06, 4.33, 4.35, 4.8 , 4.84, 5.95, 6.69, 7.86, 8.65, 9.44, 9.5 ,
       9.89])

'second quantile = 4.82'

array([4.84, 5.95, 6.69, 7.86, 8.65, 9.44, 9.5 , 9.89])

'third quantile = 8.06'

array([8.65, 9.44, 9.5 , 9.89])

In [38]:
# mask all values below zero as 0
mask = A<0
A[mask] = 0

display(np.round(A,2))

array([[8.65, 0.  , 0.  , 6.69],
       [5.95, 2.06, 4.35, 1.77],
       [9.5 , 4.8 , 7.86, 4.84],
       [4.33, 9.89, 1.55, 9.44]])

In [40]:
# swapping columns in matrix
A_swapped =  A[:,[3,1,2,0]]

display(np.round(A_swapped,2))

array([[6.69, 0.  , 0.  , 8.65],
       [1.77, 2.06, 4.35, 5.95],
       [4.84, 4.8 , 7.86, 9.5 ],
       [9.44, 9.89, 1.55, 4.33]])