In [17]:
import numpy as np

In [18]:
## reshape
I = np.random.uniform(size=12, low=-10, high=10)
A = I.reshape(3,4)
B = I.reshape(2,6)

np.round(A,2),np.round(B,2)

(array([[-6.21,  8.1 ,  6.55, -0.8 ],
        [-4.77,  9.63,  1.86,  9.41],
        [-9.38,  6.28, -5.49,  6.16]]),
 array([[-6.21,  8.1 ,  6.55, -0.8 , -4.77,  9.63],
        [ 1.86,  9.41, -9.38,  6.28, -5.49,  6.16]]))

In [19]:
## broadcasting
V = np.random.uniform(size=3, low=-10, high=10)

A_plus_v = A + V[:, None]

display(V)
display(A)
display(A_plus_v)

array([-0.28913752, -6.41126205,  2.27788718])

array([[-6.21364741,  8.10457804,  6.54748433, -0.80126745],
       [-4.77301429,  9.62907088,  1.86315813,  9.41300338],
       [-9.37881035,  6.27813494, -5.49093408,  6.15832532]])

array([[ -6.50278493,   7.81544052,   6.25834681,  -1.09040497],
       [-11.18427634,   3.21780882,  -4.54810392,   3.00174133],
       [ -7.10092317,   8.55602212,  -3.2130469 ,   8.4362125 ]])

In [20]:
# normalisation
mean_cols = A.mean(axis=0)
std_cols = A.std(axis=0,ddof=0)

A_norm = (A - mean_cols) / std_cols

display(A_norm)

array([[ 0.29881521,  0.07347452,  1.12502309, -1.34367704],
       [ 1.04768558,  1.18635355,  0.17960858,  1.05380582],
       [-1.34650079, -1.25982806, -1.30463167,  0.28987122]])