In [32]:
import numpy as np
import pandas as pd

 i'm done choosing which problems i'm going to make from https://github.com/rougier/numpy-100/tree/master

;)

In [46]:
#
# exercises_to_make = np.random.choice(np.arange(1, 100), size=40, replace=False)
# exercises_to_make = np.sort(exercises_to_make)
# df = pd.DataFrame(exercises_to_make)
#
# df.to_csv('numpy_have_spoken.csv')
#
# df

In [57]:
df = pd.read_csv('numpy_have_spoken.csv')
exercises_to_make = np.array(df[['0']]).reshape(1,40)
exercises_to_make

array([[ 2,  3,  4,  6,  7,  9, 10, 12, 17, 22, 23, 28, 29, 30, 34, 35,
        39, 41, 42, 43, 50, 51, 59, 61, 63, 64, 66, 67, 70, 72, 74, 77,
        81, 82, 83, 85, 86, 89, 92, 95]])

2. Print the numpy version and the configuration (★☆☆)

In [60]:
# print(np.version)
# print(np.show_config())


3. Create a null vector of size 10 (★☆☆)

In [64]:
null_vector = np.zeros(10, dtype=int)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

4. How to find the memory size of any array (★☆☆)

In [71]:
n = np.random.randint(10, 1000)

any_vector = np.zeros(n)

any_vector.size

757

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [73]:
null_vector = np.zeros(10, dtype=int)
null_vector[5] = 1

null_vector

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

7. Create a vector with values ranging from 10 to 49

In [74]:
n = np.random.randint(10, 1000)
vector = np.random.choice(np.arange(1, 49), size=n)

vector

array([25, 32, 48, 11, 34,  5, 20, 17,  8,  9, 14, 13, 33, 24, 17,  3, 22,
       28, 18, 18, 22, 31,  3, 36, 42,  7,  4, 48, 15, 16,  5, 24, 33, 25,
       29, 32, 34, 33,  1, 23, 12, 13,  9, 34, 34, 39, 12, 45,  1, 28,  9,
        6, 32,  9, 37, 33, 43, 18, 47, 33, 12, 33, 31, 46,  5, 11,  2, 45,
       45,  6, 43, 21,  5, 16, 11, 22, 14, 16, 22,  3,  4, 40, 40, 48,  2,
       18, 18, 30,  4,  9, 19, 30, 42, 32, 43, 40, 37, 30, 32, 27, 14, 25,
        9, 15, 19, 40,  1, 43, 39, 18, 46, 47, 42, 10, 42, 31, 48, 42, 34,
       45, 30, 33,  2, 16, 39, 47, 37, 32, 17, 33,  2, 33, 47, 27, 32, 10,
       11, 23, 26, 34, 28, 40, 36, 28,  3, 12,  3, 44, 28, 12, 30, 20, 25,
       25,  6, 35,  2,  1, 36, 35, 11, 32, 22, 19,  4,  5, 30,  9, 20, 14,
       22, 10, 40, 43,  4, 46, 17, 41, 22, 25, 19,  4, 11, 17,  3, 16, 22,
       43,  9, 44, 12, 40, 46, 14, 33, 24,  5, 19, 33, 32, 18, 11, 37, 19,
       22, 41, 47, 32, 39, 18, 23, 43, 18, 21, 25, 29, 10,  4, 39,  8, 24,
       27, 46, 35, 41, 27

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [75]:
matrix = np.random.choice(np.arange(0, 8), size=9).reshape(3,3)

matrix

array([[3, 4, 5],
       [2, 5, 7],
       [2, 5, 7]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [78]:
vector = np.array([1,2,0,0,4,0])

non_zero_i = np.nonzero(vector)[0]
non_zero_i

array([0, 1, 4])

12. Create a 3x3x3 array with random values (★☆☆)

In [87]:
matrix = np.random.uniform(size=3*3*3).reshape(3,3,3)



array([[[0.35865066, 0.60384019, 0.37477038],
        [0.05856284, 0.42723507, 0.08545968],
        [0.24933412, 0.96659838, 0.63783876]],

       [[0.25813066, 0.03100162, 0.95829811],
        [0.7986916 , 0.43643918, 0.21957457],
        [0.52091861, 0.27616999, 0.00263392]],

       [[0.07050671, 0.48493348, 0.88108491],
        [0.69489122, 0.01274197, 0.51242055],
        [0.95511299, 0.02182999, 0.04458098]]])


17. What is the result of the following expression? (★☆☆)





In [79]:
display(0 * np.nan)
display(np.nan == np.nan)
display(np.inf > np.nan)
display(np.nan - np.nan)
display(np.nan in set([np.nan]))
display(0.3 == 3 * 0.1)

nan

False

False

nan

True

False

22. Normalize a 5x5 random matrix (★☆☆)

In [84]:
matrix = np.random.uniform(size=25).reshape(5,5)

mean_cols = matrix.mean(axis=0)
std_cols = matrix.std(axis=0,ddof=0)

matrix_norm = (matrix - mean_cols) / std_cols

display(np.round(matrix_norm.mean(axis=0)))
display(np.round(matrix_norm.std(axis=0)))
display(matrix_norm)

array([-0.,  0., -0.,  0.,  0.])

array([1., 1., 1., 1., 1.])

array([[ 1.0536916 ,  0.7824164 , -0.02636779, -1.05291028, -0.42591058],
       [-0.56664813,  0.95002112, -1.13773229,  1.16330939,  0.43539401],
       [ 1.05933922, -1.28881163, -0.6541859 ,  1.004362  ,  0.7263257 ],
       [ 0.01762931,  0.70712384,  1.81020593, -1.23117652, -1.75187994],
       [-1.564012  , -1.15074972,  0.00808004,  0.11641541,  1.01607081]])

28. What are the result of the following expressions? (★☆☆)

In [85]:
display(np.array(0) / np.array(0))
display(np.array(0) // np.array(0))
display(np.array([np.nan]).astype(int).astype(float))

/tmp/ipykernel_6005/3274373259.py:1: RuntimeWarning: invalid value encountered in divide
  display(np.array(0) / np.array(0))


np.float64(nan)

/tmp/ipykernel_6005/3274373259.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  display(np.array(0) // np.array(0))


np.int64(0)

/tmp/ipykernel_6005/3274373259.py:3: RuntimeWarning: invalid value encountered in cast
  display(np.array([np.nan]).astype(int).astype(float))


array([-9.22337204e+18])

29. How to round away from zero a float array ? (★☆☆)

In [90]:
n = np.random.randint(10, 1000)

x = np.random.uniform(low=-10, high=10, size=n)
y = np.sign(x) * np.ceil(np.abs(x))

y

array([  7.,   9.,   2.,  -7.,   5.,   9.,   4.,   2.,   8.,   8.,  -5.,
        -6.,   8.,   7.,   7.,  -5.,   4.,  -7.,   2.,  -7.,  -8.,  -5.,
         3.,   3.,   2.,  -6.,   8.,   6.,   3.,  -3.,   6.,   5.,   7.,
        -2.,   3.,  -5.,   2.,   7., -10.,  -5.,   2.,  -7.,  -2.,  -2.,
        -2.,   3., -10.,   5.,  -3.,  -3.,  -7.,  -4.,   6.,  -3., -10.,
        -6.,  -4.,   3.,   5.,  -8.,  -8.,   8.,   5.,   7.,  -2.,  -6.,
        -1.,  -4.,  -9.,  -1.,   1.,  -6.,  -5., -10.,   5.,  -7.,  -3.,
         7.,  -1.,   2.,   1.,  -8.,   9.,   2., -10.,  -5.,   5.,   6.,
        -2.,  -5.,  -7.,   7.,  -2.,  -7.,  -2.,   5.,   7.,   4.,   3.,
         2.,  -6., -10.,  -9., -10.,   5.,   3.,   5.,  -8.,  -5.,   1.,
         4., -10.,   2.,   4.,  -4.,   8.,  -7.,  -8.,  -6.,  -9.,   9.,
        -1.,   9.,  -5.,  -9.,  -7.,  -7.,  -8.,  -5.,  -5.,   4.,   4.,
         7.,   5.,  -5.,  -5.,  -6.,   3.,  -5.,  -3.,   3.,   3.,  10.,
        -9.,   3.,   2.,   2.,   3.,  10., -10.,  -

30. How to find common values between two arrays? (★☆☆)

In [94]:
n = np.random.randint(10, 1000)

x = np.random.randint(10, 100, size=n)
y = np.random.randint(10, 100, size=n)

common = np.intersect1d(x, y)

common

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [95]:
dates = np.arange(
    np.datetime64("2016-07-01"),
    np.datetime64("2016-08-01"),
    np.timedelta64(1, "D")
)

dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [97]:
a =  np.random.randint(10, 1000)
b =  np.random.randint(10, 1000)


A = np.random.uniform(size=a*b).reshape(a,b)
B = np.random.uniform(size=a*b).reshape(a,b)

B += A
A *= -0.5
B *= A

B

array([[-0.09083708, -0.25039311, -0.08581359, ..., -0.02475203,
        -0.13834084, -0.0778834 ],
       [-0.02068519, -0.13297975, -0.21421013, ..., -0.70881367,
        -0.12289706, -0.18505105],
       [-0.34403614, -0.09156487, -0.00882415, ..., -0.01848909,
        -0.16591908, -0.78814031],
       ...,
       [-0.19698656, -0.48056554, -0.01272784, ..., -0.87158471,
        -0.03273767, -0.11009633],
       [-0.03366473, -0.4196247 , -0.5946573 , ..., -0.51320756,
        -0.13132272, -0.71547426],
       [-0.00228519, -0.13317285, -0.0891459 , ..., -0.03094124,
        -0.04570163, -0.62954981]], shape=(41, 349))

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [100]:
vector = np.random.uniform(low=0.0, high=1.0,size=10)
vector

array([0.05556731, 0.48413734, 0.70756168, 0.19059317, 0.39728137,
       0.50984147, 0.54167963, 0.189485  , 0.48775627, 0.26373099])

41. How to sum a small array faster than np.sum? (★★☆)

In [103]:
big_array = np.random.uniform(low=0.0, high=1.0,size=10000)
small_array = np.random.uniform(low=0.0, high=1.0,size=10)


%time big_array.sum()
%time np.sum(big_array)
%time np.add.reduce(big_array)

%time small_array.sum()
%time np.sum(small_array)
%time np.add.reduce(small_array)


CPU times: user 60 μs, sys: 4 μs, total: 64 μs
Wall time: 76.5 μs
CPU times: user 31 μs, sys: 2 μs, total: 33 μs
Wall time: 40.1 μs
CPU times: user 16 μs, sys: 0 ns, total: 16 μs
Wall time: 18.6 μs
CPU times: user 11 μs, sys: 0 ns, total: 11 μs
Wall time: 12.9 μs
CPU times: user 15 μs, sys: 0 ns, total: 15 μs
Wall time: 16.7 μs
CPU times: user 7 μs, sys: 0 ns, total: 7 μs
Wall time: 8.34 μs


np.float64(3.4463784029426647)

42. Consider two random arrays A and B, check if they are equal (★★☆)

In [107]:
A = np.random.randint(0, 10, size=5)
B = np.random.randint(0, 10, size=5)
# B = A.copy()


display(np.array_equal(A, B))
display(A == B)
display(np.all(A == B))

False

array([ True, False, False,  True,  True])

np.False_

43. Make an array immutable (read-only) (★★☆)

In [108]:
n = np.random.randint(10, 1000)

x = np.random.randint(10, 100, size=n)
x.flags.writeable = False

50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [114]:
vector = np.random.uniform(low=0.0, high=100.0 ,size=100)
value_to_find = np.random.uniform(low=0.0, high=100.0)

i = np.argmin(np.abs(vector  - value_to_find))
closest = vector [i]

print(vector)
print(value_to_find, i, closest)

[42.58558249 66.54799286 56.07377335  7.37082562 33.88037806 29.28866457
 25.32499252 77.4821447  56.23275599 49.77628695 80.63349219 78.24054453
 29.96404192 96.80873392 91.10751756 46.74672746 92.10103188 79.9356498
 42.23777197  1.51085849 25.3130345  91.79918448 63.39349893 29.74287316
 90.48637589 70.79755131 63.35014409 83.8317829  84.78480268 46.77155961
 28.73763049 49.00509561 24.88179468 66.09329964 62.55323506  7.7911475
 49.56545116 98.29176556 78.86739857 42.86872229 17.20593199 63.12865121
 98.29503068 56.18685937 93.27045864 79.76069808 94.01553463 90.56889822
  5.21472222 71.11429505 54.60210981 76.28201747 34.00552292  2.50443776
 80.40815833 49.79009045 28.03023078 90.03832771 89.11937514 21.16194704
 62.27304522 18.78553151  3.34804663 64.62820405 84.52708592 22.39621317
 46.6044106  28.62637833 93.17903105  8.29907403  6.7575462   3.36081791
  4.6494038  42.83792144 52.57386747 44.31944097 19.88788466 54.44515602
 92.23370369 46.46959779 65.56678263 50.17153594 25.6

51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

59. How to sort an array by the nth column? (★★☆)

61. Find the nearest value from a given value in an array (★★☆)

63. Create an array class that has a name attribute (★★☆)

64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

72. How to swap two rows of an array? (★★★)

74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

82. Compute a matrix rank (★★★)

83. How to find the most frequent value in an array?

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

89. How to get the n largest values of an array (★★★)

In [86]:
i = np.random.randint(10, 1000)
n = np.random.randint(1, i)

x = np.random.uniform(size=i)

x = np.sort(x)[::-1]

n_largest_values = x[:n]

display(f'{n} largest values from {i} values array')
n_largest_values

'72 largest values from 188 values array'

array([0.99938293, 0.99777589, 0.99147777, 0.97591269, 0.97555129,
       0.97037082, 0.96997259, 0.96399264, 0.95066731, 0.94766479,
       0.93620119, 0.92144167, 0.91980863, 0.91720658, 0.91096104,
       0.91065515, 0.90471807, 0.89726486, 0.8873792 , 0.8814949 ,
       0.87971892, 0.87760957, 0.87306171, 0.86846638, 0.86559783,
       0.86276272, 0.85726769, 0.85198957, 0.83308674, 0.8242054 ,
       0.80551825, 0.7992668 , 0.79413713, 0.7810105 , 0.75968262,
       0.75712882, 0.75578862, 0.755619  , 0.74900078, 0.74450724,
       0.73952362, 0.73704691, 0.7358417 , 0.73319878, 0.72842647,
       0.72725292, 0.72244624, 0.72210772, 0.72197257, 0.71717198,
       0.71576452, 0.71270465, 0.70001035, 0.69083543, 0.69035558,
       0.68994909, 0.67878329, 0.66737803, 0.66579929, 0.66387637,
       0.66088583, 0.66065195, 0.6579973 , 0.65284414, 0.65004273,
       0.64933632, 0.64281555, 0.64210894, 0.63765084, 0.63132769,
       0.62716358, 0.62472444])

92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
A = np.random.uniform(size=30)*10

A = np.round(A).reshape(10,3)
A = np.astype(A,int)

# Adding equal rows to test (up to 7)
how_much_equal_rows = np.random.randint(1, 8)

# rows to replace
rows_to_replace = np.random.choice(np.arange(1, 10), size=how_much_equal_rows, replace=False)

for i in rows_to_replace:
    A[i] = [i,i,i]

display(A)

unequal_rows = A[np.ptp(A, axis=1) != 0]

display("Unequal rows" ,unequal_rows)


95. Convert a vector of ints into a matrix binary representation (★★★)